Failed to execute code at iteration 0: Traceback (most recent call last):
  File "/home/anyaji/grounded-edit/playground/data/art_photos_slide_13/iter_0/gpt-4o/code.py", line 53, in <module>
    left_img = slide.shapes.add_picture(rabbit_img_path, Inches(2), Inches(3), height=Inches(4))
  File "/home/anyaji/anaconda3/envs/edits/lib/python3.10/site-packages/pptx/shapes/shapetree.py", line 370, in add_picture
    image_part, rId = self.part.get_or_add_image_part(image_file)
  File "/home/anyaji/anaconda3/envs/edits/lib/python3.10/site-packages/pptx/parts/slide.py", line 50, in get_or_add_image_part
    image_part = self._package.get_or_add_image_part(image_file)
  File "/home/anyaji/anaconda3/envs/edits/lib/python3.10/site-packages/pptx/package.py", line 38, in get_or_add_image_part
    return self._image_parts.get_or_add_image_part(image_file)
  File "/home/anyaji/anaconda3/envs/edits/lib/python3.10/site-packages/pptx/package.py", line 153, in get_or_add_image_part
    image = Image.from_file(image_file)
  File "/home/anyaji/anaconda3/envs/edits/lib/python3.10/site-packages/pptx/parts/image.py", line 163, in from_file
    with open(image_file, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '../../media/high_res_hare.jpg'
